#!/usr/bin/env bash
[colors]
background=#272C36
background_alt=#2e3440
foreground=#d8dee9
foreground_alt=#93979f
primary=#8fbcbb
secondary=#80a1c0
alert=#b48ead

[bar/hlwm]
monitor = ${env:MONITOR}
width = 100%
height = 22
;offset-x = 1%
;offset-y = 1%
;radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

;line-size = 3
;line-color = #f00

border-size = 0
;border-color = #00000000

padding-left = 4
padding-right = 8

module-margin-left = 2
module-margin-right = 8

font-0 = Cantarell:style=Bold:pixelsize=11;3
font-1 = Cantarell:pixelsize=11;3
font-2 = SauceCodePro NF:style=Bold:size=18;5

modules-left = info-hlwm-workspaces xwindow
modules-center =
modules-right =  wlan eth pulseaudio xkeyboard date battery

tray-position = none
tray-padding = 4
;tray-background = #0063ff

;wm-restack = i3

override-redirect = true

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

[module/info-hlwm-workspaces]
type = custom/script
exec = ~/.config/polybar/info-hlwm-workspaces.sh
tail = true
scroll-up = herbstclient use_index -1 --skip-visible &
scroll-down = herbstclient use_index +1 --skip-visible &

[module/xwindow]
type = internal/xwindow
label = %{T2}%title:0:0:...%
label-maxlen = ${env:MAX_TITLE_WIDTH}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = "%{A1:gnome-control-center keyboard &:}%{A3:gnome-control-center region &:}%{A}%{A}  "
format-prefix-foreground = ${colors.foreground}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 0
label-indicator-margin = 0
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground_alt}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground_alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = ${env:WIFI_ADAPTER}
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground_alt}

ramp-signal-0 = "%{A3:gnome-control-center wifi &:}%{A}  "
ramp-signal-foreground = ${colors.foreground_alt}

[module/eth]
type = internal/network
interface = ${env:ETHERNET_ADAPTER}
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = "%{A3:gnome-control-center network &:}%{A}  "
format-connected-prefix-foreground = ${colors.foreground_alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground_alt}

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = "%{A3:gnome-control-center datetime &:}%{A}  "
format-prefix-foreground = ${colors.foreground}
format-underline = #0a6cf5

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false
format-volume = <label-volume>
label-volume = %{A3:gnome-control-center sound &:}%{A}  %percentage%%
label-volume-foreground = ${root.foreground}

format-muted = <label-muted>
label-muted = %{A3:gnome-control-center sound &:}%{A}   %percentage%%
label-muted-foreground = #666

bar-volume-width = 8
bar-volume-foreground-0 = ${colors.secondary}
bar-volume-foreground-1 = ${colors.secondary}
bar-volume-foreground-2 = ${colors.secondary}
bar-volume-foreground-3 = ${colors.secondary}
bar-volume-foreground-4 = ${colors.secondary}
bar-volume-foreground-5 = ${colors.primary}
bar-volume-foreground-6 = ${colors.alert}
bar-volume-gradient = false
bar-volume-indicator = 
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground_alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

label-full = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
format-full = <label-full>
format-full-prefix-foreground = ${colors.foreground}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A} "
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
ramp-capacity-1-foreground = ${colors.secondary}
ramp-capacity-2 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
ramp-capacity-3 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
ramp-capacity-foreground = ${colors.foreground}
ramp-capacity-4 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "

animation-charging-0 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-charging-1 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-charging-2 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-charging-3 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-charging-4 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-charging-foreground = ${colors.foreground}
animation-charging-framerate = 750

animation-discharging-0 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-discharging-1 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-discharging-2 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-discharging-3 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-discharging-4 = "%{A1:bash ~/.config/herbstluftwm/scripts/power_menu.sh &:}%{A3:gnome-control-center power &:}%{A}%{A}  "
animation-discharging-foreground = ${colors.foreground}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground_alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground_alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini
