# Keep window open after video ends
keep-open=yes

# Dracula background
background=color
background-color="#FF232530"

# OSD Dracula theme
osd-color="#bd93f9"
osd-border-color="#bd93f9"
osd-shadow-color="#bd93f9"
osd-back-color="#bd93f9"

osd-font-size=24
osd-border-size=0

# Disable default OSC (ModernZ replaces it)
osc=no
osd-bar=no
